### ISSUE TITLE
Sorting of pac lists

### ISSUE THREAD

**Issue by dwsr36** [txthinking/pac#12]
#### Describe actual behavior
Symbols (such as - and .) are ignored when using the command `sort`, such as `addWhite.sh`.

#### What is your expected behavior
Symbols will not be ignored when sorting the lists.

#### Specifications like the version of the project, operating system, or hardware
Only white list were resorted in https://github.com/txthinking/pac/commit/5944ef79051cd0f0ce8c04947a4e098e97da2950. Before this commit, symbols in all the lists are not ignored when sorting.

#### Steps to reproduce the problem
The following are merely examples, not real websites.
1. Add a website in white list `addWhite.sh abc.com`
2. Add another website `addWhite.sh abcb.com`
3. `abc.com` will stand behind `abcb.com` because the dot is ignored.

#### Possible solution
Since it is more practical to treat all characters equal, a solution has been provided in https://stackoverflow.com/questions/5982531/behaviour-of-gnu-sort-command-with-non-letter-ascii-characters-such-as-dot-or. We can add `LC_COLLATE=C` before `sort` in all .sh files starting with add. In my opinion, a better choice is to revert last two commits before modifying .sh files.

**Comment by txthinking** [comment]
Yes. Set LC_COLLATE=C can get traditional sort order that uses native byte values. This is not a functional defect.  I think we don't need to care the old commits. Just modifying scripts, running scripts is enough.

**Comment by dwsr36** [comment]
https://github.com/txthinking/pac/pull/13
